server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: eureka
                    uri: https://github.com/DeyvidGar/microservicio-example
                    search-paths: config-service/config-data
    application:
        name: config-service