spring:
  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=user
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true

server:
  port: 8084
